# -*- coding: utf-8 -*-
"""check_palindrome.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B_jZqfylg2f-JzivC-ZVrxW5ZQBjprHY
"""

#check it is palindrome or not
def ispalindrome(s):
    return s == s[::-1]
s = input("Enter a string: ")
ans = ispalindrome(s)
if ans:
    print("Yes")
else:
    print("No")