# -*- coding: utf-8 -*-
"""city_state.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B_jZqfylg2f-JzivC-ZVrxW5ZQBjprHY
"""

#whether city in telangana state or not
c = 0;
cname = input("Enter a city name: ")
cities = ["Hyderabad", "Secunderabad","Warangal"]
while cname in cities:
    c = 1
if(c == 1):
    print("Present in state of telangana")