# -*- coding: utf-8 -*-
"""digits_count.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B_jZqfylg2f-JzivC-ZVrxW5ZQBjprHY
"""

string = input("Enter a string: ")
letters = sum(c.isalpha() for c in string)
digits = sum(c.isdigit() for c in string)
print(f"Letters: {letters}, Digits: {digits}")

