# -*- coding: utf-8 -*-
"""function.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B_jZqfylg2f-JzivC-ZVrxW5ZQBjprHY
"""

def vol_cube(a):
    volume = a**3
    return volume
s=int(input("Enter side: "))
vol_cube(s)