# -*- coding: utf-8 -*-
"""largest_string.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B_jZqfylg2f-JzivC-ZVrxW5ZQBjprHY
"""

#finding largest of a string
test_list = ['ram','sita','purple','knowledge']
lengths = [len(s) for s in test_list]
largest_index = lengths.index(max(lengths))
largest_string = test_list[largest_index]
print("largest_string is: "+ largest_string)