# -*- coding: utf-8 -*-
"""length_string.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B_jZqfylg2f-JzivC-ZVrxW5ZQBjprHY
"""

#length of a string
string = input("Enter a string: ")
count = 0
for s in string:
    count = count+1
print("Length :",count)