# -*- coding: utf-8 -*-
"""menu_prices.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B_jZqfylg2f-JzivC-ZVrxW5ZQBjprHY
"""

#program to write menu with prices
def menu():
    dishes = ["1. rice", "2. chicken", "3. noodles"]
    for i in dishes:
        print(i)
def submenu():
    menu()
    c = int(input("enter your choice: "))
    rice_dishes = { " 1. Veg Fried Rice":120, " 2. Veg Biryani":250, " 3. Veg Biryani":300, " 4. Veg pulao":120, " 5. Ghee Rice":130, " 6. Curd Rice":80}
    chicken_dishes = { " 1. chicken noodles":200, " 2. chicken 65":180, " 3. chicken lollipop":180, " 4. chicken manchuriya":100, " 5. chicken mandi":220," 6. chicken shawarma":320}
    noodles_dishes = { " 1. Veg noodles":80, " 2. panner noodles":100, " 3. chicken noodles":100, " 4. mushroom noodles":120}
    print(list(rice_dishes.keys()))
    print(list(chicken_dishes.keys()))
    print(list(noodles_dishes.keys()))
    if c == 1:
        for x in rice_dishes:
            print(x)
    elif c == 2:
        for x in chicken_dishes:
            print(x)
    elif c == 3:
        for x in noodles_dishes:
            print(x)
        else:
            print("sorry! wrong choice")
    g = int(input("Enter your item: "))
    if g <= 5:
        print("Here you go!!")
    else:
        print("Check again....sorry")
    i = g-1
    if c <= 3:
        if c == 1:
            p = list(rice_dishes.values())[i]
            print(p)
        elif c== 2:
            q = list(chicken_dishes.values())[i]
            print(q)
        elif c == 3:
            r = list(noodles_dishes.values())[i]
            print(r)
        else:
            print("Please check your choice again ...")
    submenu()

