# -*- coding: utf-8 -*-
"""no_0_6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B_jZqfylg2f-JzivC-ZVrxW5ZQBjprHY
"""

for i in range(7):
    if i != 3 and i != 6:
        print(i)

