# -*- coding: utf-8 -*-
"""pattern.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B_jZqfylg2f-JzivC-ZVrxW5ZQBjprHY
"""

for i in range(1, 6):
    print('* ' * i)
for i in range(4, 0, -1):
    print('* ' * i)