# -*- coding: utf-8 -*-
"""rainbow.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B_jZqfylg2f-JzivC-ZVrxW5ZQBjprHY
"""

#rainbow colors
def rainbow(s):
    colors = ""
    return(colors.join(s))
s = ["violet ","indigo ","blue ","green ","yellow ","orange ","red "]
print(rainbow(s))