# -*- coding: utf-8 -*-
"""rev_string.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B_jZqfylg2f-JzivC-ZVrxW5ZQBjprHY
"""

#reverse a string
name = "radha"[::-1]
print(name)