# -*- coding: utf-8 -*-
"""reverse_digits.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B_jZqfylg2f-JzivC-ZVrxW5ZQBjprHY
"""

#reverse of a digit
num = int(input("Enter number: "))
rev_number = 0
while(num > 0):
    remainder = num % 10
    rev_number = (rev_number*10) + remainder
    num = num // 10
print("reverse is : ",rev_number)