# -*- coding: utf-8 -*-
"""reverse.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B_jZqfylg2f-JzivC-ZVrxW5ZQBjprHY
"""

word = input("Enter a word: ")
reversed_word = word[::-1]
print("Reversed word:", reversed_word)

