# -*- coding: utf-8 -*-
"""sort_array.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B_jZqfylg2f-JzivC-ZVrxW5ZQBjprHY
"""

#sorting an array
arr = [4,5,7,8,3,9,6,1,10,2]
temp = 0
max_size = len(arr)
print("The elements of the array before sorting: ")
for i in range(0,max_size):
    print(arr[i],end = "")
print()
for i in range(0,max_size):
    for j in range(i+1,len(arr)):
        if(arr[i]>arr[j]):
            temp = arr[i]
            arr[i] = arr[j]
            arr[j] = temp
print("The elements of the array after sorting: ")
for i in range(0,max_size):
    print(arr[i],end = "")