# -*- coding: utf-8 -*-
"""string_list.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B_jZqfylg2f-JzivC-ZVrxW5ZQBjprHY
"""

#string into list
string = input("Enter a string: ")
list = [i for i in string]
print(list)