# -*- coding: utf-8 -*-
"""swap_2_numbers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B_jZqfylg2f-JzivC-ZVrxW5ZQBjprHY
"""

#swapping of two numbers
x = input("Enter value of x: ")
y = input("Enter value of y: ")
temp = x
x = y
y = temp
print("The value of x after swapping:{} ",format(x))
print("The value of y after swapping:{} ",format(y))